### ISSUE TITLE
language server will not initialzed when this plugin installed. 

### ISSUE THREAD

**Issue by RickyYCheng** [benknoble/vim-racket#9]
os: windows 11, env: wsl2 

install `nvim` 0.6.1 and `Plug` 
install node(12) and yarn for `coc.nvim` 
install `coc.nvim`
install `racket` and `drracket` 
update wslg to use gui app. 
`raco pkg install racket-langserver`
configure `CocConfig` to enable auto complelemtation. 

everything was fine so far. 
ready to install `benknoble/vim-racket` 

`Plug 'benknoble/vim-racket'` and `:PlugInstall`

if we open a `.rkt` or `.ss` file, the syntax highlighting will be enabled due to the `vim-racket` plugin, but the language server or code complementation will not be enabled. (nvim just not show `Initializing languageserver.racket`)

**Comment by benknoble** [comment]
I don't have built-in support for CoC in this plugin. I did contribute to ALE so that it could run racket-langserver, though.

My recommendation would be to configure CoC in the usual way to use racket-langserver as the LSP server for racket files.

**Comment by RickyYChan** [comment]
> 我在此插件中没有对CoC的内置支持。不过，我确实为ALE做出了贡献，以便它可以运行球拍服务器。
> 
> 我的建议是以通常的方式配置CoC，以使用球拍服务器作为球拍文件的LSP服务器。

alright

**Comment by RickyYCheng** [comment]
> I don't have built-in support for CoC in this plugin. I did contribute to ALE so that it could run racket-langserver, though.
> 
> My recommendation would be to configure CoC in the usual way to use racket-langserver as the LSP server for racket files.

alright
